# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: goraft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'goraft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgoraft.proto\x12\x05proto\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\r\n\x05index\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"\x9f\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12 \n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0f.proto.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"K\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0eleader_address\x18\x03 \x01(\t2\xd9\x01\n\x04Node\x12\x44\n\x0bRequestVote\x12\x19.proto.RequestVoteRequest\x1a\x1a.proto.RequestVoteResponse\x12J\n\rAppendEntries\x12\x1b.proto.AppendEntriesRequest\x1a\x1c.proto.AppendEntriesResponse\x12?\n\x0e\x45xecuteCommand\x12\x15.proto.CommandRequest\x1a\x16.proto.CommandResponseB\x14Z\x12giraft/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'goraft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022giraft/proto;proto'
  _globals['_REQUESTVOTEREQUEST']._serialized_start=23
  _globals['_REQUESTVOTEREQUEST']._serialized_end=126
  _globals['_REQUESTVOTERESPONSE']._serialized_start=128
  _globals['_REQUESTVOTERESPONSE']._serialized_end=185
  _globals['_LOGENTRY']._serialized_start=187
  _globals['_LOGENTRY']._serialized_end=243
  _globals['_APPENDENTRIESREQUEST']._serialized_start=246
  _globals['_APPENDENTRIESREQUEST']._serialized_end=405
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=407
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=461
  _globals['_COMMANDREQUEST']._serialized_start=463
  _globals['_COMMANDREQUEST']._serialized_end=496
  _globals['_COMMANDRESPONSE']._serialized_start=498
  _globals['_COMMANDRESPONSE']._serialized_end=573
  _globals['_NODE']._serialized_start=576
  _globals['_NODE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
