// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntryCommandType int32

const (
	LogEntryCommandType_LOG_ENTRY_COMMAND_SET    LogEntryCommandType = 0
	LogEntryCommandType_LOG_ENTRY_COMMAND_DELETE LogEntryCommandType = 1
)

// Enum value maps for LogEntryCommandType.
var (
	LogEntryCommandType_name = map[int32]string{
		0: "LOG_ENTRY_COMMAND_SET",
		1: "LOG_ENTRY_COMMAND_DELETE",
	}
	LogEntryCommandType_value = map[string]int32{
		"LOG_ENTRY_COMMAND_SET":    0,
		"LOG_ENTRY_COMMAND_DELETE": 1,
	}
)

func (x LogEntryCommandType) Enum() *LogEntryCommandType {
	p := new(LogEntryCommandType)
	*p = x
	return p
}

func (x LogEntryCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntryCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (LogEntryCommandType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x LogEntryCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntryCommandType.Descriptor instead.
func (LogEntryCommandType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_SET    CommandType = 0
	CommandType_COMMAND_TYPE_DELETE CommandType = 1
	CommandType_COMMAND_TYPE_GET    CommandType = 2
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_SET",
		1: "COMMAND_TYPE_DELETE",
		2: "COMMAND_TYPE_GET",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_SET":    0,
		"COMMAND_TYPE_DELETE": 1,
		"COMMAND_TYPE_GET":    2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

type NodeRole int32

const (
	NodeRole_ROLE_FOLLOWER  NodeRole = 0
	NodeRole_ROLE_CANDIDATE NodeRole = 1
	NodeRole_ROLE_LEADER    NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "ROLE_FOLLOWER",
		1: "ROLE_CANDIDATE",
		2: "ROLE_LEADER",
	}
	NodeRole_value = map[string]int32{
		"ROLE_FOLLOWER":  0,
		"ROLE_CANDIDATE": 1,
		"ROLE_LEADER":    2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[2].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[2]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

type NodeStatus int32

const (
	NodeStatus_STATUS_STOPPED     NodeStatus = 0
	NodeStatus_STATUS_RUNNING     NodeStatus = 1
	NodeStatus_STATUS_UNREACHABLE NodeStatus = 2
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "STATUS_STOPPED",
		1: "STATUS_RUNNING",
		2: "STATUS_UNREACHABLE",
	}
	NodeStatus_value = map[string]int32{
		"STATUS_STOPPED":     0,
		"STATUS_RUNNING":     1,
		"STATUS_UNREACHABLE": 2,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[3].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[3]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

type LogEntryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LogEntryCommandType    `protobuf:"varint,1,opt,name=type,proto3,enum=LogEntryCommandType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"` // Only for SET command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryCommand) Reset() {
	*x = LogEntryCommand{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryCommand) ProtoMessage() {}

func (x *LogEntryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryCommand.ProtoReflect.Descriptor instead.
func (*LogEntryCommand) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntryCommand) GetType() LogEntryCommandType {
	if x != nil {
		return x.Type
	}
	return LogEntryCommandType_LOG_ENTRY_COMMAND_SET
}

func (x *LogEntryCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntryCommand) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Command       *LogEntryCommand       `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() *LogEntryCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type AppendEntriesArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      int64                  `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesArguments) Reset() {
	*x = AppendEntriesArguments{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesArguments) ProtoMessage() {}

func (x *AppendEntriesArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesArguments.ProtoReflect.Descriptor instead.
func (*AppendEntriesArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesArguments) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesArguments) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesArguments) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesArguments) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesArguments) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesArguments) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestVoteArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   int64                  `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArguments) Reset() {
	*x = RequestVoteArguments{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArguments) ProtoMessage() {}

func (x *RequestVoteArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArguments.ProtoReflect.Descriptor instead.
func (*RequestVoteArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteArguments) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArguments) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteArguments) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteArguments) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type CommandExecutionArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       CommandType            `protobuf:"varint,1,opt,name=command,proto3,enum=CommandType" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionArguments) Reset() {
	*x = CommandExecutionArguments{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionArguments) ProtoMessage() {}

func (x *CommandExecutionArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionArguments.ProtoReflect.Descriptor instead.
func (*CommandExecutionArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *CommandExecutionArguments) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_COMMAND_TYPE_SET
}

func (x *CommandExecutionArguments) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommandExecutionArguments) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type CommandExecutionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`        // For GET command
	LeaderId      *int64                 `protobuf:"varint,3,opt,name=leaderId,proto3,oneof" json:"leaderId,omitempty"` // For redirecting clients to the leader if not the current node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionReply) Reset() {
	*x = CommandExecutionReply{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionReply) ProtoMessage() {}

func (x *CommandExecutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionReply.ProtoReflect.Descriptor instead.
func (*CommandExecutionReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *CommandExecutionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandExecutionReply) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *CommandExecutionReply) GetLeaderId() int64 {
	if x != nil && x.LeaderId != nil {
		return *x.LeaderId
	}
	return 0
}

type StreamNodeStateArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNodeStateArguments) Reset() {
	*x = StreamNodeStateArguments{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNodeStateArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNodeStateArguments) ProtoMessage() {}

func (x *StreamNodeStateArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNodeStateArguments.ProtoReflect.Descriptor instead.
func (*StreamNodeStateArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *StreamNodeStateArguments) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StreamNodeStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Role          NodeRole               `protobuf:"varint,3,opt,name=role,proto3,enum=NodeRole" json:"role,omitempty"`
	Term          int64                  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      *int64                 `protobuf:"varint,5,opt,name=leaderId,proto3,oneof" json:"leaderId,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,6,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,7,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastApplied   int64                  `protobuf:"varint,8,opt,name=lastApplied,proto3" json:"lastApplied,omitempty"`
	Status        NodeStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNodeStateReply) Reset() {
	*x = StreamNodeStateReply{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNodeStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNodeStateReply) ProtoMessage() {}

func (x *StreamNodeStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNodeStateReply.ProtoReflect.Descriptor instead.
func (*StreamNodeStateReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *StreamNodeStateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamNodeStateReply) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *StreamNodeStateReply) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_ROLE_FOLLOWER
}

func (x *StreamNodeStateReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StreamNodeStateReply) GetLeaderId() int64 {
	if x != nil && x.LeaderId != nil {
		return *x.LeaderId
	}
	return 0
}

func (x *StreamNodeStateReply) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StreamNodeStateReply) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *StreamNodeStateReply) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *StreamNodeStateReply) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_STATUS_STOPPED
}

type StreamNodesStatesReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Nodes         []*StreamNodeStateReply `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNodesStatesReply) Reset() {
	*x = StreamNodesStatesReply{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNodesStatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNodesStatesReply) ProtoMessage() {}

func (x *StreamNodesStatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNodesStatesReply.ProtoReflect.Descriptor instead.
func (*StreamNodesStatesReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *StreamNodesStatesReply) GetNodes() []*StreamNodeStateReply {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfoArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          *string                `protobuf:"bytes,2,opt,name=addr,proto3,oneof" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoArguments) Reset() {
	*x = NodeInfoArguments{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoArguments) ProtoMessage() {}

func (x *NodeInfoArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoArguments.ProtoReflect.Descriptor instead.
func (*NodeInfoArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *NodeInfoArguments) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeInfoArguments) GetAddr() string {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x1a\x1bgoogle/protobuf/empty.proto\"r\n" +
	"\x0fLogEntryCommand\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.LogEntryCommandTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"`\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12*\n" +
	"\acommand\x18\x03 \x01(\v2\x10.LogEntryCommandR\acommand\"\xd7\x01\n" +
	"\x16AppendEntriesArguments\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\x03R\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x03R\vprevLogTerm\x12#\n" +
	"\aentries\x18\x05 \x03(\v2\t.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x03R\fleaderCommit\"B\n" +
	"\x12AppendEntriesReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x92\x01\n" +
	"\x14RequestVoteArguments\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\x03R\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm\"H\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"z\n" +
	"\x19CommandExecutionArguments\x12&\n" +
	"\acommand\x18\x01 \x01(\x0e2\f.CommandTypeR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\x84\x01\n" +
	"\x15CommandExecutionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x1f\n" +
	"\bleaderId\x18\x03 \x01(\x03H\x01R\bleaderId\x88\x01\x01B\b\n" +
	"\x06_valueB\v\n" +
	"\t_leaderId\"*\n" +
	"\x18StreamNodeStateArguments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa8\x02\n" +
	"\x14StreamNodeStateReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1d\n" +
	"\x04role\x18\x03 \x01(\x0e2\t.NodeRoleR\x04role\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x03R\x04term\x12\x1f\n" +
	"\bleaderId\x18\x05 \x01(\x03H\x00R\bleaderId\x88\x01\x01\x12 \n" +
	"\vcommitIndex\x18\x06 \x01(\x03R\vcommitIndex\x12\"\n" +
	"\flastLogIndex\x18\a \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastApplied\x18\b \x01(\x03R\vlastApplied\x12#\n" +
	"\x06status\x18\t \x01(\x0e2\v.NodeStatusR\x06statusB\v\n" +
	"\t_leaderId\"E\n" +
	"\x16StreamNodesStatesReply\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.StreamNodeStateReplyR\x05nodes\"E\n" +
	"\x11NodeInfoArguments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04addr\x18\x02 \x01(\tH\x00R\x04addr\x88\x01\x01B\a\n" +
	"\x05_addr*N\n" +
	"\x13LogEntryCommandType\x12\x19\n" +
	"\x15LOG_ENTRY_COMMAND_SET\x10\x00\x12\x1c\n" +
	"\x18LOG_ENTRY_COMMAND_DELETE\x10\x01*R\n" +
	"\vCommandType\x12\x14\n" +
	"\x10COMMAND_TYPE_SET\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_DELETE\x10\x01\x12\x14\n" +
	"\x10COMMAND_TYPE_GET\x10\x02*B\n" +
	"\bNodeRole\x12\x11\n" +
	"\rROLE_FOLLOWER\x10\x00\x12\x12\n" +
	"\x0eROLE_CANDIDATE\x10\x01\x12\x0f\n" +
	"\vROLE_LEADER\x10\x02*L\n" +
	"\n" +
	"NodeStatus\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x16\n" +
	"\x12STATUS_UNREACHABLE\x10\x022\xc8\x01\n" +
	"\bRaftNode\x12=\n" +
	"\rAppendEntries\x12\x17.AppendEntriesArguments\x1a\x13.AppendEntriesReply\x127\n" +
	"\vRequestVote\x12\x15.RequestVoteArguments\x1a\x11.RequestVoteReply\x12D\n" +
	"\x0eExecuteCommand\x12\x1a.CommandExecutionArguments\x1a\x16.CommandExecutionReply2\x8d\x02\n" +
	"\vRaftCluster\x12F\n" +
	"\x11StreamNodesStates\x12\x16.google.protobuf.Empty\x1a\x17.StreamNodesStatesReply0\x01\x12E\n" +
	"\x0fStreamNodeState\x12\x19.StreamNodeStateArguments\x1a\x15.StreamNodeStateReply0\x01\x125\n" +
	"\aAddNode\x12\x12.NodeInfoArguments\x1a\x16.google.protobuf.Empty\x128\n" +
	"\n" +
	"RemoveNode\x12\x12.NodeInfoArguments\x1a\x16.google.protobuf.EmptyB\x11Z\x0fraft/autogen;pbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_node_proto_goTypes = []any{
	(LogEntryCommandType)(0),          // 0: LogEntryCommandType
	(CommandType)(0),                  // 1: CommandType
	(NodeRole)(0),                     // 2: NodeRole
	(NodeStatus)(0),                   // 3: NodeStatus
	(*LogEntryCommand)(nil),           // 4: LogEntryCommand
	(*LogEntry)(nil),                  // 5: LogEntry
	(*AppendEntriesArguments)(nil),    // 6: AppendEntriesArguments
	(*AppendEntriesReply)(nil),        // 7: AppendEntriesReply
	(*RequestVoteArguments)(nil),      // 8: RequestVoteArguments
	(*RequestVoteReply)(nil),          // 9: RequestVoteReply
	(*CommandExecutionArguments)(nil), // 10: CommandExecutionArguments
	(*CommandExecutionReply)(nil),     // 11: CommandExecutionReply
	(*StreamNodeStateArguments)(nil),  // 12: StreamNodeStateArguments
	(*StreamNodeStateReply)(nil),      // 13: StreamNodeStateReply
	(*StreamNodesStatesReply)(nil),    // 14: StreamNodesStatesReply
	(*NodeInfoArguments)(nil),         // 15: NodeInfoArguments
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_node_proto_depIdxs = []int32{
	0,  // 0: LogEntryCommand.type:type_name -> LogEntryCommandType
	4,  // 1: LogEntry.command:type_name -> LogEntryCommand
	5,  // 2: AppendEntriesArguments.entries:type_name -> LogEntry
	1,  // 3: CommandExecutionArguments.command:type_name -> CommandType
	2,  // 4: StreamNodeStateReply.role:type_name -> NodeRole
	3,  // 5: StreamNodeStateReply.status:type_name -> NodeStatus
	13, // 6: StreamNodesStatesReply.nodes:type_name -> StreamNodeStateReply
	6,  // 7: RaftNode.AppendEntries:input_type -> AppendEntriesArguments
	8,  // 8: RaftNode.RequestVote:input_type -> RequestVoteArguments
	10, // 9: RaftNode.ExecuteCommand:input_type -> CommandExecutionArguments
	16, // 10: RaftCluster.StreamNodesStates:input_type -> google.protobuf.Empty
	12, // 11: RaftCluster.StreamNodeState:input_type -> StreamNodeStateArguments
	15, // 12: RaftCluster.AddNode:input_type -> NodeInfoArguments
	15, // 13: RaftCluster.RemoveNode:input_type -> NodeInfoArguments
	7,  // 14: RaftNode.AppendEntries:output_type -> AppendEntriesReply
	9,  // 15: RaftNode.RequestVote:output_type -> RequestVoteReply
	11, // 16: RaftNode.ExecuteCommand:output_type -> CommandExecutionReply
	14, // 17: RaftCluster.StreamNodesStates:output_type -> StreamNodesStatesReply
	13, // 18: RaftCluster.StreamNodeState:output_type -> StreamNodeStateReply
	16, // 19: RaftCluster.AddNode:output_type -> google.protobuf.Empty
	16, // 20: RaftCluster.RemoveNode:output_type -> google.protobuf.Empty
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{}
	file_node_proto_msgTypes[6].OneofWrappers = []any{}
	file_node_proto_msgTypes[7].OneofWrappers = []any{}
	file_node_proto_msgTypes[9].OneofWrappers = []any{}
	file_node_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
