// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntryCommandType int32

const (
	LogEntryCommandType_LOG_ENTRY_COMMAND_SET    LogEntryCommandType = 0
	LogEntryCommandType_LOG_ENTRY_COMMAND_DELETE LogEntryCommandType = 1
)

// Enum value maps for LogEntryCommandType.
var (
	LogEntryCommandType_name = map[int32]string{
		0: "LOG_ENTRY_COMMAND_SET",
		1: "LOG_ENTRY_COMMAND_DELETE",
	}
	LogEntryCommandType_value = map[string]int32{
		"LOG_ENTRY_COMMAND_SET":    0,
		"LOG_ENTRY_COMMAND_DELETE": 1,
	}
)

func (x LogEntryCommandType) Enum() *LogEntryCommandType {
	p := new(LogEntryCommandType)
	*p = x
	return p
}

func (x LogEntryCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntryCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (LogEntryCommandType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x LogEntryCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *LogEntryCommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = LogEntryCommandType(num)
	return nil
}

// Deprecated: Use LogEntryCommandType.Descriptor instead.
func (LogEntryCommandType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_SET    CommandType = 0
	CommandType_COMMAND_TYPE_DELETE CommandType = 1
	CommandType_COMMAND_TYPE_GET    CommandType = 2
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_SET",
		1: "COMMAND_TYPE_DELETE",
		2: "COMMAND_TYPE_GET",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_SET":    0,
		"COMMAND_TYPE_DELETE": 1,
		"COMMAND_TYPE_GET":    2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CommandType(num)
	return nil
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

type LogEntryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *LogEntryCommandType   `protobuf:"varint,1,req,name=type,enum=LogEntryCommandType" json:"type,omitempty"`
	Key           *string                `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"` // Only for SET command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryCommand) Reset() {
	*x = LogEntryCommand{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryCommand) ProtoMessage() {}

func (x *LogEntryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryCommand.ProtoReflect.Descriptor instead.
func (*LogEntryCommand) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntryCommand) GetType() LogEntryCommandType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return LogEntryCommandType_LOG_ENTRY_COMMAND_SET
}

func (x *LogEntryCommand) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *LogEntryCommand) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *int64                 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Term          *int64                 `protobuf:"varint,2,req,name=term" json:"term,omitempty"`
	Command       *LogEntryCommand       `protobuf:"bytes,3,req,name=command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() *LogEntryCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type AppendEntriesArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *int64                 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	LeaderId      *int64                 `protobuf:"varint,2,req,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex  *int64                 `protobuf:"varint,3,req,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm   *int64                 `protobuf:"varint,4,req,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	LeaderCommit  *int64                 `protobuf:"varint,6,req,name=leaderCommit" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesArguments) Reset() {
	*x = AppendEntriesArguments{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesArguments) ProtoMessage() {}

func (x *AppendEntriesArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesArguments.ProtoReflect.Descriptor instead.
func (*AppendEntriesArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesArguments) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *AppendEntriesArguments) GetLeaderId() int64 {
	if x != nil && x.LeaderId != nil {
		return *x.LeaderId
	}
	return 0
}

func (x *AppendEntriesArguments) GetPrevLogIndex() int64 {
	if x != nil && x.PrevLogIndex != nil {
		return *x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesArguments) GetPrevLogTerm() int64 {
	if x != nil && x.PrevLogTerm != nil {
		return *x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesArguments) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesArguments) GetLeaderCommit() int64 {
	if x != nil && x.LeaderCommit != nil {
		return *x.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *int64                 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	Success       *bool                  `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesReply) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type RequestVoteArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *int64                 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	CandidateId   *int64                 `protobuf:"varint,2,req,name=candidateId" json:"candidateId,omitempty"`
	LastLogIndex  *int64                 `protobuf:"varint,3,req,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm   *int64                 `protobuf:"varint,4,req,name=lastLogTerm" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArguments) Reset() {
	*x = RequestVoteArguments{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArguments) ProtoMessage() {}

func (x *RequestVoteArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArguments.ProtoReflect.Descriptor instead.
func (*RequestVoteArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteArguments) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *RequestVoteArguments) GetCandidateId() int64 {
	if x != nil && x.CandidateId != nil {
		return *x.CandidateId
	}
	return 0
}

func (x *RequestVoteArguments) GetLastLogIndex() int64 {
	if x != nil && x.LastLogIndex != nil {
		return *x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteArguments) GetLastLogTerm() int64 {
	if x != nil && x.LastLogTerm != nil {
		return *x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *int64                 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	VoteGranted   *bool                  `protobuf:"varint,2,req,name=voteGranted" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteReply) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil && x.VoteGranted != nil {
		return *x.VoteGranted
	}
	return false
}

type CommandExecutionArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandType           `protobuf:"varint,1,req,name=command,enum=CommandType" json:"command,omitempty"`
	Key           *string                `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionArguments) Reset() {
	*x = CommandExecutionArguments{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionArguments) ProtoMessage() {}

func (x *CommandExecutionArguments) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionArguments.ProtoReflect.Descriptor instead.
func (*CommandExecutionArguments) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *CommandExecutionArguments) GetCommand() CommandType {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return CommandType_COMMAND_TYPE_SET
}

func (x *CommandExecutionArguments) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *CommandExecutionArguments) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type CommandExecutionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`        // For GET command
	LeaderId      *int64                 `protobuf:"varint,3,req,name=leaderId" json:"leaderId,omitempty"` // For redirecting clients to the leader if not the current node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionReply) Reset() {
	*x = CommandExecutionReply{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionReply) ProtoMessage() {}

func (x *CommandExecutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionReply.ProtoReflect.Descriptor instead.
func (*CommandExecutionReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *CommandExecutionReply) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *CommandExecutionReply) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *CommandExecutionReply) GetLeaderId() int64 {
	if x != nil && x.LeaderId != nil {
		return *x.LeaderId
	}
	return 0
}

type StreamStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *int64                 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	CommitIndex   *int64                 `protobuf:"varint,2,req,name=commitIndex" json:"commitIndex,omitempty"` // NOTE: add other fields as needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateReply) Reset() {
	*x = StreamStateReply{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateReply) ProtoMessage() {}

func (x *StreamStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateReply.ProtoReflect.Descriptor instead.
func (*StreamStateReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *StreamStateReply) GetTerm() int64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *StreamStateReply) GetCommitIndex() int64 {
	if x != nil && x.CommitIndex != nil {
		return *x.CommitIndex
	}
	return 0
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x0fLogEntryCommand\x12(\n" +
	"\x04type\x18\x01 \x02(\x0e2\x14.LogEntryCommandTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"`\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x02(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x02(\x03R\x04term\x12*\n" +
	"\acommand\x18\x03 \x02(\v2\x10.LogEntryCommandR\acommand\"\xd7\x01\n" +
	"\x16AppendEntriesArguments\x12\x12\n" +
	"\x04term\x18\x01 \x02(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x02(\x03R\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x02(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x02(\x03R\vprevLogTerm\x12#\n" +
	"\aentries\x18\x05 \x03(\v2\t.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x02(\x03R\fleaderCommit\"B\n" +
	"\x12AppendEntriesReply\x12\x12\n" +
	"\x04term\x18\x01 \x02(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x02(\bR\asuccess\"\x92\x01\n" +
	"\x14RequestVoteArguments\x12\x12\n" +
	"\x04term\x18\x01 \x02(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x02(\x03R\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x02(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x02(\x03R\vlastLogTerm\"H\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x02(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x02(\bR\vvoteGranted\"k\n" +
	"\x19CommandExecutionArguments\x12&\n" +
	"\acommand\x18\x01 \x02(\x0e2\f.CommandTypeR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"c\n" +
	"\x15CommandExecutionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x02(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\bleaderId\x18\x03 \x02(\x03R\bleaderId\"H\n" +
	"\x10StreamStateReply\x12\x12\n" +
	"\x04term\x18\x01 \x02(\x03R\x04term\x12 \n" +
	"\vcommitIndex\x18\x02 \x02(\x03R\vcommitIndex*N\n" +
	"\x13LogEntryCommandType\x12\x19\n" +
	"\x15LOG_ENTRY_COMMAND_SET\x10\x00\x12\x1c\n" +
	"\x18LOG_ENTRY_COMMAND_DELETE\x10\x01*R\n" +
	"\vCommandType\x12\x14\n" +
	"\x10COMMAND_TYPE_SET\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_DELETE\x10\x01\x12\x14\n" +
	"\x10COMMAND_TYPE_GET\x10\x022\x84\x02\n" +
	"\bRaftNode\x12=\n" +
	"\rAppendEntries\x12\x17.AppendEntriesArguments\x1a\x13.AppendEntriesReply\x127\n" +
	"\vRequestVote\x12\x15.RequestVoteArguments\x1a\x11.RequestVoteReply\x12D\n" +
	"\x0eExecuteCommand\x12\x1a.CommandExecutionArguments\x1a\x16.CommandExecutionReply\x12:\n" +
	"\vStreamState\x12\x16.google.protobuf.Empty\x1a\x11.StreamStateReply0\x01B\x12Z\x10raft/proto;proto"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_node_proto_goTypes = []any{
	(LogEntryCommandType)(0),          // 0: LogEntryCommandType
	(CommandType)(0),                  // 1: CommandType
	(*LogEntryCommand)(nil),           // 2: LogEntryCommand
	(*LogEntry)(nil),                  // 3: LogEntry
	(*AppendEntriesArguments)(nil),    // 4: AppendEntriesArguments
	(*AppendEntriesReply)(nil),        // 5: AppendEntriesReply
	(*RequestVoteArguments)(nil),      // 6: RequestVoteArguments
	(*RequestVoteReply)(nil),          // 7: RequestVoteReply
	(*CommandExecutionArguments)(nil), // 8: CommandExecutionArguments
	(*CommandExecutionReply)(nil),     // 9: CommandExecutionReply
	(*StreamStateReply)(nil),          // 10: StreamStateReply
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_node_proto_depIdxs = []int32{
	0,  // 0: LogEntryCommand.type:type_name -> LogEntryCommandType
	2,  // 1: LogEntry.command:type_name -> LogEntryCommand
	3,  // 2: AppendEntriesArguments.entries:type_name -> LogEntry
	1,  // 3: CommandExecutionArguments.command:type_name -> CommandType
	4,  // 4: RaftNode.AppendEntries:input_type -> AppendEntriesArguments
	6,  // 5: RaftNode.RequestVote:input_type -> RequestVoteArguments
	8,  // 6: RaftNode.ExecuteCommand:input_type -> CommandExecutionArguments
	11, // 7: RaftNode.StreamState:input_type -> google.protobuf.Empty
	5,  // 8: RaftNode.AppendEntries:output_type -> AppendEntriesReply
	7,  // 9: RaftNode.RequestVote:output_type -> RequestVoteReply
	9,  // 10: RaftNode.ExecuteCommand:output_type -> CommandExecutionReply
	10, // 11: RaftNode.StreamState:output_type -> StreamStateReply
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
