syntax = "proto3";
option go_package = "raft/autogen;pb";

import "google/protobuf/empty.proto";

enum LogEntryCommandType {
  LOG_ENTRY_COMMAND_SET = 0;
  LOG_ENTRY_COMMAND_DELETE = 1;
}

message LogEntryCommand {
  LogEntryCommandType type = 1;
  string key = 2;
  optional string value = 3; // Only for SET command
}

message LogEntry {
  int64 index = 1;
  int64 term = 2;
  LogEntryCommand command = 3;
}

message AppendEntriesArguments {
  int64 term = 1;
  int64 leaderId = 2;
  int64 prevLogIndex = 3;
  int64 prevLogTerm = 4;
  repeated LogEntry entries = 5;
  int64 leaderCommit = 6;
}

message AppendEntriesReply {
  int64 term = 1;
  bool success = 2;
}

message RequestVoteArguments {
  int64 term = 1;
  int64 candidateId = 2;
  int64 lastLogIndex = 3;
  int64 lastLogTerm = 4;
}

message RequestVoteReply {
  int64 term = 1;
  bool voteGranted = 2;
}

enum CommandType {
  COMMAND_TYPE_SET = 0;
  COMMAND_TYPE_DELETE = 1;
  COMMAND_TYPE_GET = 2;
}

message CommandExecutionArguments {
  CommandType command = 1;
  string key = 2;
  optional string value = 3;
}

message CommandExecutionReply {
  bool success = 1;
  optional string value = 2; // For GET command
  optional int64 leaderId = 3; // For redirecting clients to the leader if not the current node
}

enum NodeRole {
  ROLE_FOLLOWER = 0;
  ROLE_CANDIDATE = 1;
  ROLE_LEADER = 2;
}

enum NodeStatus {
  STATUS_STOPPED = 0;
  STATUS_RUNNING = 1;
  STATUS_UNREACHABLE = 2;
}

message StreamNodeStateArguments {
  int64 id = 1;
}

message StreamNodeStateReply {
  int64 id = 1;
  string addr = 2;
  NodeRole role = 3;
  int64 term = 4;
  optional int64 leaderId = 5;
  int64 commitIndex = 6;
  int64 lastLogIndex = 7;
  int64 lastApplied = 8;
  NodeStatus status = 9;
}

message StreamNodesStatesReply {
  repeated StreamNodeStateReply nodes = 1;
}

service RaftNode {
  rpc AppendEntries(AppendEntriesArguments) returns (AppendEntriesReply);
  rpc RequestVote(RequestVoteArguments) returns (RequestVoteReply);
  rpc ExecuteCommand(CommandExecutionArguments) returns (CommandExecutionReply);
}

message NodeInfoArguments {
  int64 id = 1;
  optional string addr = 2;
}

service RaftCluster {
  rpc StreamNodesStates(google.protobuf.Empty) returns (stream StreamNodesStatesReply);
  rpc StreamNodeState(StreamNodeStateArguments) returns (stream StreamNodeStateReply);
  rpc AddNode(NodeInfoArguments) returns (google.protobuf.Empty);
  rpc RemoveNode(NodeInfoArguments) returns (google.protobuf.Empty);
}
